### ISSUE TITLE
PR request

### ISSUE THREAD

**Issue by vasspilka** [foxnewsnetwork/fox#1]
Hey really like the utility functions, what I write a lot is something like this,

```
defmodule XXX.DateHelper do

  def date_to_text(date) do
    date
    |> Date.to_string()
    |> String.split("-")
    |> Enum.reverse()
    |> Enum.join("/")
  end

  def text_to_date(date) do
    date
    |> String.split("/")
    |> Enum.reverse()
    |> Enum.join("-")
    |> Date.from_iso8601!
  end
end
```

may I do a PR to include this in fox ^.^ ? 🦊

**Comment by foxnewsnetwork** [comment]
Sure, I welcome contributions. Please be sure to write tests

**Comment by vasspilka** [comment]
closing in favor of #2 :) just realised this one the first issue/PR I have oppened to be #1
